### ISSUE TITLE
Switch from SQLite to MySQL

### ISSUE THREAD

**Issue by 20Koen02** [20Koen02/HomeAPI#1]
I am currently using SQLite to store the device configuration.
I would like to use MySQL instead of SQLite.

I am using Python with FastAPI
Take a look at /app/database/database.py and https://fastapi.tiangolo.com/tutorial/sql-databases/

Please comment and I will assign you 👍🏼

**Comment by raulsoledispa** [comment]
Hi, I would like to can help you. Can you assign me it?

**Comment by BatoolMM** [comment]
Hi, can I also help you with it, please?

**Comment by andrewmiko** [comment]
@20Koen02 I can work on this one too.

**Comment by 20Koen02** [comment]
@raulsoledispa was the first one to comment so I assigned you

**Comment by 20Koen02** [comment]
#2 Thanks Raul for the awesome work!
